web:
  image: nginx:alpine
  ports:
    - "8000:80"
  volumes:
    - ./server:/opt/www
    - ./config/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: php:7.3-fpm-alpine
  volumes:
    - ./server:/opt/www
